name: Build and deploy Node.js app to Azure Web App - spc-tracker

on:
  push:
    branches:
      - azure
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node.js dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build (if needed)
        run: npm run build --if-present

      - name: Zip app (exclude node_modules, .env, release.zip, etc.)
        run: |
          zip -r release.zip . -x "*.git*" "*node_modules*" "*.env" "*release.zip*" "*.db-wal" "*.db-shm" "*.pyc" "*__pycache__*"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip build
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_22E66D7856B346839B4A831A5887E16B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_552A26896A5242D1B72C1A2946D6CA70 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3735CA28971D41FE8BF4DED7700AE6EF }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'spc-tracker'
          slot-name: 'Production'
          package: .
