name: Build & deploy Node.js app to Azure Web App

on:
  push:
    branches: [ dev ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies & build
        working-directory: ./backend
        run: |
          npm ci
          npm run build --if-present

      # ⚡️ Remove manual zip step — let the deploy action package ./backend for you
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tn-npi-stats-dev'
          package: './backend'                    # ← point at backend folder
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
